/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "testjni.h"

jstring JNICALL Java_net_sarangnamu_jni_TestJNI_testJni (JNIEnv *env, jobject)
{
	return env->NewStringUTF(env, "Hello from JNI !");
}
