/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sarangnamu_jni_TestJNI */

#ifndef _Included_net_sarangnamu_jni_TestJNI
#define _Included_net_sarangnamu_jni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sarangnamu_jni_TestJNI
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sarangnamu_jni_TestJNI_testJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
